before_script:
  - apt-get update -yqq
  - apt-get install swig -yqq
  - apt-get install libssl-dev -yqq
  - apt-get install python3-dev -yqq
  - sed -i 's#ssh://git@gitlab.com#https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com#g' setup.py

stages:
  - test
  - build
  - deploy

test:py37-sqlite:
  stage: test
  image: python:3.7
  variables:
      CFLAGS: "-O0"
      DB_CACHE: "~/cache"
      TOX_TESTENV_PASSENV: "CFLAGS DB_CACHE"
  script:
    - pip install tox
    - tox -e py37-sqlite

test:py37-postgresql:
  stage: test
  image: python:3.7
  tags:
      - postgres
  services:
      - postgres
  variables:
      CFLAGS: "-O0"
      DB_CACHE: "~/cache"
      TOX_TESTENV_PASSENV: "CFLAGS DB_CACHE"
      POSTGRES_HOST_AUTH_METHOD: "trust"
      POSTGRESQL_URI: "postgresql://postgres:@postgres:5432/"
  script:
    - pip install tox
    - tox -e py37-postgresql
